model:
  name: FontIdentification1Flow
  args:
    in_dim: 3
    in_size: 64
    n_hidden: 1028
    drop: 0.12
  freeze: False
  checkpoint: ./checkpoint/model.pt
optim:
  lr: 0.0001
  batch_size: 48
  step: 20
  gamma: 0.1
  n_epoch: 30
  continue_training: False
data:
  dir_path: ../../dataset/font_images_all
  train_csv: ./data/train_pair_font_all.csv
  val_csv: ./data/val_pair_font_all.csv
  test_csv: ./data/test_pair_font_all.csv
log: ./checkpoint